#pragma once
#include <iostream>
#include <SFML/Graphics.hpp>
#include <SFML/System.hpp>
#include <SFML/Audio.hpp>
#include <SFML/Window.hpp>
#include <SFML/Network.hpp>
#include <ostream>
#include <fstream>
#include <vector>
#include <list>
#include <set>
#include <map>
#include <math.h>
#include <string>